###
GET http://localhost:4004/odata/v4/nautical/VOYTYP




###
POST  http://localhost:4004/odata/v4/nautical/VOYTYP
Content-Type: application/json

{
"VOYNM": "100000",
"VLEGN": "1234567890",
"PORTC":"89jh",
"PORTN": "Port City",
"LOCNAM": "OilRef1",
"PDIST": "1500.456",
"VSPEED": "12",
"PPDAYS": "3",
"VSDAYS": "5",
"VETAD": "2023-12-10",
"VETAT": null,
"VETDD": "2023-12-15",
"VETDT": null,
"VWEAD": "1",
"PSTAT": "Plan",
"MATNR": "M123456789",
"MAKTX": "Material Description",
"CARGS": "5678",
"CARGU": "Tonnes",
"OTHCO_code": null,
"FRCOST_code": null,
"TOTCO_code": null
}

###
DELETE  http://localhost:4004/odata/v4/nautical/NAVOYGIP/

###
PATCH   http://localhost:4004/odata/v4/nautical/NAVOYGIP/VOY2
Content-Type: application/json

{

"PORTN": "PCity"

}